defaults:
  - _self_
  - wandb: _defaults
 
version: 0.0.1
seed: 0
mode: pytorch

hydra:
  run:
    dir: ./logs/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}